### ISSUE TITLE
se publicará algún contenido?

### ISSUE THREAD

**Issue by oldlastman** [catedra-rtve-uc3m/smart-public#1]
Veo que la cátedra lleva almenos 1 año en github pero no ha presentado nado mas allá de su propia web..
se planea abrir algún contenido?
gracias por la información

**Comment by chemaar** [comment]
Buenos días:

Gracias por la pregunta! La difusión es algo que tenemos planeado a través de distintos canales como publicaciones y presentaciones, etc.  que serán compiladas aquí,

Atentamente,
